name: Update Banner

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Download banner
        run: |
          curl -L "https://api.mcstatus.io/v2/widget/java/phymlymc.com" -o status.png

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add status.png

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Update banner"
            git push
          fi
